In [8]:
import numpy as np
arr = np.array([2,4,6,8])

arr/2

array([1., 2., 3., 4.])

In [10]:
list = [2,4,6,8]

list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [13]:
import numpy as np
arr = np.array([5,10,15,20])

arr*2

array([10, 20, 30, 40])

In [15]:
cars = ["Ford", "Volvo", "BMW"]
print(cars)

['Ford', 'Volvo', 'BMW']


In [19]:
cars = ["Ford", "Volvo", "BMW"]
x = cars[0]
print(x)

Ford


In [21]:
cars = ["Ford", "Volvo", "BMW"]

cars[0] = "Toyota"

print(cars)


['Toyota', 'Volvo', 'BMW']


In [23]:
cars = ["Ford", "Volvo", "BMW"]

for x in cars:
  print(x)

Ford
Volvo
BMW


In [26]:
cars = ["Ford", "Volvo", "BMW"]

x = len(cars)
print(x)

3


In [28]:
cars = ["Ford", "Volvo", "BMW"]

cars.append("Honda")

print(cars)

['Ford', 'Volvo', 'BMW', 'Honda']


In [38]:
student = ['Paska,','Riri','Neva','Najla','Caca']
student [3] = 'Dah'
student [0] = 'Abdul'
for x in student:
    print(x)

Abdul
Riri
Neva
Dah
Caca


In [39]:
student = ['Paska,','Riri','Neva','Najla','Caca']
student [3] = 'Dah'
student [0] = 'Abdul'
student.append('Vicky')
for x in student:
    print(x)

Abdul
Riri
Neva
Dah
Caca
Vicky


In [50]:
student = ['Paska,','Riri','Neva','Najla','Caca']
student [3] = 'Dah'
student [0] = 'Abdul'
student.append('Vicky')
student.pop(1)
student.pop(4)
for x in student:
    print(x)

Abdul
Neva
Dah
Caca


In [47]:
student = ['Vicky','Fadhlan','Dzikri','Fajril','Aripin']
x = student.copy()

print(x)


['Vicky', 'Fadhlan', 'Dzikri', 'Fajril', 'Aripin']


In [51]:
student = ['Vicky','Fadhlan','Dzikri','Fajril','Aripin']
x = student.count("Vicky")

print(x)

1


In [53]:
student_male = ['Vicky','Fadhlan','Dzikri']
student_female = ['Neva','Najla','Riri']

student_male.extend(student_female)

print(student_male)

['Vicky', 'Fadhlan', 'Dzikri', 'Neva', 'Najla', 'Riri']


In [57]:
import numpy as np
#Creating list
list = [1,2,3,4]

#Creating numpy array
sample_array = np.array(list)

print("List in python :",list)

print('Numpy Array in python :',sample_array)

List in python : [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


In [58]:
#Creating list
list_1 = [1,2,3]
list_2 = [5,6,7]
list_3 = [9,10,11]

#Creating numpy array
sample_array = np.array([list_1,
                        list_2,
                        list_3])
print('Numpy multi dimensional array in python\n ',sample_array)

Numpy multi dimensional array in python
  [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
